version: '3.7'
services:
  server:
    # build:
      # context: ./backend
      # dockerfile: Dockerfile
    image: node-app
    container_name: myapp-node-server
    command: /backend/node_modules/.bin/nodemon server.js
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_CONNECTION_STRING=$MONGODB_STRING
    networks:
      - backend
      - frontend

  client:
    # build:
      # context: ./frontend
      # dockerfile: Dockerfile
    image: react-app
    container_name: myapp-react-client
    command: npm start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  backend:
  frontend:

